version: "3.2"
services:
  nodejs:
    build: 
      context: .
    image: amakundu/nodejs-mysql-app
    networks:
      - frontend
      - backend
    environment:
      - MYSQL_HOST=moe-mysql-app
      - MYSQL_USER=root
      - MYSQL_PASS=rupesh27
      - MYSQL_DB=test
    volumes:
      - ./www/:/var/www/html/
    ports:
      - "30001:8005"
    container_name: nodejs-app
  mysql:
    image: mysql:5.7
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
      - MYSQL_PASSWORD=rupesh27
      - MYSQL_DATABASE=text
    container_name: mysql-app
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    depends_on:
      - mysql
    networks:
      - backend
    ports:
      - "30002:80"
    environment:
      - PMA_HOST= mysql-app
      - PMA_PORT= 3306
    volumes:
      - /sessions
    container_name: phpmyadmin-app
networks:
  frontend:
  backend: